# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow validates the packaging of the Java project using Maven.

name: Packaging check Maven

on: pull_request


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
            submodules: 'true'
      - name: Set up CMake and maven
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake maven
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build native libraries
        run: |
          scripts/build-native.sh
      - name: Build with Maven
        run: |
          export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$GITHUB_WORKSPACE/build/lib
          export LIBRARY_PATH=$LIBRARY_PATH:$GITHUB_WORKSPACE/build/lib
          mvn -B package --file pom.xml
